/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "git-2021-01-31-d16b0a4-QtAV"
#endif /* AVUTIL_FFVERSION_H */
